DELETE FROM classes;
INSERT INTO classes (title, value) VALUES ("Section", "books");
INSERT INTO classes (title, value) VALUES ("Section", "electronics");
INSERT INTO classes (title, value) VALUES ("Section", "clothes");
INSERT INTO classes (title, value) VALUES ("Section", "furniture");
INSERT INTO classes (title, value) VALUES ("Section", "miscellaneous");
INSERT INTO classes (title, value) VALUES ("Condition", "new");
INSERT INTO classes (title, value) VALUES ("Condition", "good");
INSERT INTO classes (title, value) VALUES ("Condition", "moderate");
INSERT INTO classes (title, value) VALUES ("Condition", "poor");